# Generated by Django 4.0 on 2022-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollow',
            options={'ordering': ('-created',)},
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('user_id', 'following_user_id'), name='users follow eachother one time'),
        ),
    ]
