# Generated by Django 4.0 on 2022-08-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_unique post title for user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
