# Generated by Django 4.0 on 2022-10-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
