# Generated by Django 4.0 on 2022-10-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_remove_post_images_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
