# Generated by Django 4.0 on 2022-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
